@host = http://localhost:3001/api
#########
######### Retrieve all users
#########
GET {{host}}/user 
content-type: application/json
#########
######### Search users
######### query = search 
GET {{host}}/user/search?text=
content-type: application/json


#########
######### Insert userr
#########
POST {{host}}/user 
content-type: application/json

{
    "fullName": "Dianne Pu Ramos",
    "mobileNumber": "09782922202"
}
#########
######### Update user
######### query = _id
PUT {{host}}/user?_id=62e7925fb2ffb3f9ef227252
content-type: application/json

{
   "fullName": "Dianne Pu Ramos",
    "mobileNumber": "09782922203"
}
